### ISSUE TITLE
Another Infinite Loop

### ISSUE THREAD

**Issue by kdbertel** [aws/aws-sdk-ios#470]
Naturally, shortly after closing #468 I end up re-finding the infinite loop I had encountered in the first place.

To reiterate some details: this is in Xcode 7.3.1 (7D1014) with CocoaPods 0.39.0 on OS X 10.11.6.

I am working on a very simple application that will use Cognito User Pools to authenticate users against Cognito so that they can be authorized to download files from S3.

Here is my App Delegate:

```
#import "AppDelegate.h"
#import "AwsConstants.h"
#import <AWSCore/AWSCore.h>
#import <AWSCognito/AWSCognito.h>
#import <AWSCognitoIdentityProvider/AWSCognitoIdentityProvider.h>

@interface AppDelegate () <AWSCognitoIdentityInteractiveAuthenticationDelegate, AWSCognitoIdentityPasswordAuthentication>
@property (nonatomic) AWSCognitoIdentityUser *user;
@property (nonatomic) AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails*>* passwordAuthenticationCompletion;
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [AWSLogger defaultLogger].logLevel = AWSLogLevelInfo;
    AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:CognitoIdentityUserPoolRegion
                                                                                                    identityPoolId:CognitoCredentialsIdentityPoolId];
    AWSServiceConfiguration *serviceConfiguration = [[AWSServiceConfiguration alloc] initWithRegion:CognitoIdentityUserPoolRegion
                                                                                    credentialsProvider:credentialsProvider];
    AWSCognitoIdentityUserPoolConfiguration *userPoolConfiguration = [[AWSCognitoIdentityUserPoolConfiguration alloc] initWithClientId:CognitoIdentityUserPoolAppClientId
                                                                                                                          clientSecret:CognitoIdentityUserPoolAppClientSecret
                                                                                                                                poolId:CognitoIdentityUserPoolId];
    [AWSCognitoIdentityUserPool registerCognitoIdentityUserPoolWithConfiguration:serviceConfiguration
                                                           userPoolConfiguration:userPoolConfiguration
                                                                          forKey:@"UserPool"];
    AWSCognitoIdentityUserPool *pool = [AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:@"UserPool"];
    pool.delegate = self;
    [credentialsProvider setIdentityProviderManagerOnce:pool];

    self.user = [pool currentUser];

    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        NSLog(@"Get user details");
        [[self.user getDetails] continueWithBlock:^id _Nullable(AWSTask<AWSCognitoIdentityUserGetDeviceResponse *> * _Nonnull task) {
            dispatch_async(dispatch_get_main_queue(), ^{
                if (task.error != nil) {
                    NSLog(@"Get Details Error: %@", task.error);
                } else {
                    NSLog(@"Get Details Response %@", task.result);
                }
            });
            return nil;
        }];
    });

    return YES;
}

#pragma mark - AWSCognitoIdentityInteractiveAuthenticationDelegate

- (id<AWSCognitoIdentityPasswordAuthentication>)startPasswordAuthentication {
    NSLog(@"   ");
    NSLog(@"*****************************");
    NSLog(@"Start password authentication");
    return self;
}

#pragma mark - AWSCognitoIdentityPasswordAuthentication

- (void)getPasswordAuthenticationDetails:(AWSCognitoIdentityPasswordAuthenticationInput *)authenticationInput
  passwordAuthenticationCompletionSource:(AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails *> *)passwordAuthenticationCompletionSource {
    NSLog(@"Pool attempting to get password authentication details. Last username %@", authenticationInput.lastKnownUsername);
    self.passwordAuthenticationCompletion = passwordAuthenticationCompletionSource;
//    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        NSLog(@"User typed in auth details");
        AWSCognitoIdentityPasswordAuthenticationDetails *result = [[AWSCognitoIdentityPasswordAuthenticationDetails alloc] initWithUsername:@"test.user" password:@"correct"];
        self.passwordAuthenticationCompletion.result = result;
//    });
}

- (void)didCompletePasswordAuthenticationStepWithError:(NSError *)error {
    dispatch_async(dispatch_get_main_queue(), ^{
        if (error != nil) {
            NSLog(@"Did complete password authentication step with error %@", error);
        } else {
            NSLog(@"Did complete password authentication step successfully");
        }
        NSLog(@"***********************************************************");
    });
}

@end
```

When I run it, I get in an infinite loop where it never actually completes the password authentication step, and setting a breakpoint inside of `-getPasswordAuthenticationDetails:passwordAuthenticationCompletionSource:` shows that the stack is growing immensely. Memory climbs pretty consistently, and I have no doubt that it would be swiftly killed on an actual device instead of the simulator (I'm currently up to 1 GB of memory used from running this App Delegate, just by letting it sit).

Here is (a truncated version of) the log:

```
2016-09-20 09:53:13.182 InfiniteLoop[38212:699544] Get user details
2016-09-20 09:53:13.184 InfiniteLoop[38212:699544]    
2016-09-20 09:53:13.184 InfiniteLoop[38212:699544] *****************************
2016-09-20 09:53:13.184 InfiniteLoop[38212:699544] Start password authentication
2016-09-20 09:53:13.185 InfiniteLoop[38212:699544] Pool attempting to get password authentication details. Last username (null)
2016-09-20 09:53:13.186 InfiniteLoop[38212:699544] User typed in auth details
2016-09-20 09:53:13.204 InfiniteLoop[38212:699544]    
2016-09-20 09:53:13.204 InfiniteLoop[38212:699544] *****************************
2016-09-20 09:53:13.204 InfiniteLoop[38212:699544] Start password authentication
2016-09-20 09:53:13.206 InfiniteLoop[38212:699544] Pool attempting to get password authentication details. Last username (null)
2016-09-20 09:53:13.206 InfiniteLoop[38212:699544] User typed in auth details
2016-09-20 09:53:13.219 InfiniteLoop[38212:699544]    
2016-09-20 09:53:13.219 InfiniteLoop[38212:699544] *****************************
2016-09-20 09:53:13.219 InfiniteLoop[38212:699544] Start password authentication
2016-09-20 09:53:13.221 InfiniteLoop[38212:699544] Pool attempting to get password authentication details. Last username (null)
2016-09-20 09:53:13.221 InfiniteLoop[38212:699544] User typed in auth details
```

I am running the application (completely fresh, aside from the obvious constants in AwsConstants.h and the Pods AWSCore AWSCognito and AWSCognitoIdentityProvider all installed at version 2.4.8 per the Podfile.lock, and putting in a valid username/password for my Cognito user pool).

This is a toy example that has pulled in what I am doing in my actual application. What I have found is in my actual application, if I comment out the line `[credentialsProvider setIdentityProviderManagerOnce:pool];` and then log in, then kill the app and uncomment the line and re-run the app, it does not get into an infinite loop, and I can download a file from S3. If I try without that line in my code, then I cannot download a file from S3 (I get Access Denied); however, with that line, then a fresh attempt at a login gets an infinite loop.

I am rather lost on what is going on, or how to do this correctly. I have yet to find any documentation or tutorial online that explains how to use Cognito User Pools to manage access to S3 assets, so I've attempted to piece it together as best I can from what I've found.

**Comment by behrooziAWS** [comment]
First you should upgrade to Cocoapods 1.0 or later, it will not fix your issue but we no longer support the betas.

Regarding your issue, my best guess as to what is happening is that you have 2 attempts to get the username/password from the end user simultaneously and they are clobbering each other's completion source with a global property:

`self.passwordAuthenticationCompletion = passwordAuthenticationCompletionSource;`

The first one is running because getDetails needs a session, the second one is running because in order to access S3 you also need a session.  Can you comment out this code:
 ```
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        NSLog(@"Get user details");
        [[self.user getDetails] continueWithBlock:^id _Nullable(AWSTask<AWSCognitoIdentityUserGetDeviceResponse *> * _Nonnull task) {
            dispatch_async(dispatch_get_main_queue(), ^{
                if (task.error != nil) {
                    NSLog(@"Get Details Error: %@", task.error);
                } else {
                    NSLog(@"Get Details Response %@", task.result);
                }
            });
            return nil;
        }];
    });
```
And see if it works?  Since didCompletePasswordAuthenticationStepWithError is not being called it would seem to indicate your completion source is getting clobbered before the result is being set.

The SDK should probably be updated to serialize requests and only have one request to get a session in flight at a given time.  Normally you are displaying a ui to your end user to get the password so the recursion used to retry will not blow your stack very fast unless the end user fails for a really long time, but we can revisit how we do retries.

**Comment by kdbertel** [comment]
We are unable to update to Cocoapods 1.0. We are part of a large ecosystem all of which is on 0.39.0 and do not have time nor money in our budget to upgrade, unfortunately.

When I comment out that code, then nothing happens at all. There is no code other than what I pasted above, in the AppDelegate. There are no other calls to S3 or anything like that; the `-getDetails` is the only call I'm making where I'm reproducing this problem.

If I comment that code back in and change `self.passwordAuthenticationompletion` into a variable local to that function (and delete the property on the class), I still get the infinite loop.

**Comment by kdbertel** [comment]
In my actual app (as opposed to the toy example I've provided above), I've noticed that if I move the line `[credentialsProvider setIdentityProviderManagerOnce:pool];` into `-didCompletePasswordAuthenticationStepWithError:` on the success portion, then there is no infinite loop. At least, until I perform the logout flow; then any login-triggering thing will again launch into an infinite loop.

My suspicion given this is that there is a problematic circular reference here. Notably, the `serviceConfiguration` has to be initialized with the `credentialsProvider`, and the `AWSCognitoIdentityPool` is registered with the `serviceConfiguration`, so the `pool` we get out of that has a reference to `serviceConfiguration`, and then the `credentialsProvider` is handed a reference to `pool`, completing the circle.

There is no documentation I can find that discusses this, or references avoiding the infinite loop. Where can I find documentation on how to properly set up everything to be able to let a user log in to a Cognito User Pool and download protected S3 assets that way?

**Comment by behrooziAWS** [comment]
I created a sample project with your code and figured out what you were doing wrong.  The correct and documented way of using user pools with cognito federated identity to get credentials is http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html

Cognito user pools doesn't require AWS credentials or a credentials provider, the calls are unauthenticated.  When you are creating your instance of AWSCognitoIdentityUserPool you are passing a credentials provider which you later tie to the UserPool with setIdentityProviderManagerOnce.  It's a bit hard to explain, but I'll try to.  What is happening is that when you call getDetails, it uses the credentialsProvider tied to UserPools to get credentials to make the call to UserPools to get a session.  The credentials provider needs a session to make the call to get credentials which also calls UserPools.  So you have two things trying to get username/password from the end user at the same time fighting with each other.

The correct way do this is to create your UserPools object without a credentials provider.  Then it will get the session from UserPools and you won't have the chicken and egg problem where to get a session you need a session.

You may need to tweak this slightly because I don't have your constants file, but this should work for you:

    ```
AWSServiceConfiguration *serviceConfiguration = [[AWSServiceConfiguration alloc] initWithRegion:CognitoIdentityUserPoolRegion credentialsProvider:nil];
    AWSCognitoIdentityUserPoolConfiguration *userPoolConfiguration = [[AWSCognitoIdentityUserPoolConfiguration alloc] initWithClientId:CognitoIdentityUserPoolAppClientId
                                                                                                                          clientSecret:CognitoIdentityUserPoolAppClientSecret
                                                                                                                                poolId:CognitoIdentityUserPoolId];
    [AWSCognitoIdentityUserPool registerCognitoIdentityUserPoolWithConfiguration:serviceConfiguration userPoolConfiguration:userPoolConfiguration forKey:@"UserPool"];
    AWSCognitoIdentityUserPool *pool = [AWSCognitoIdentityUserPool CognitoIdentityUserPoolForKey:@"UserPool"];
    pool.delegate = self;
    
    AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:CognitoIdentityIdentityPoolRegion identityPoolId:CognitoCredentialsIdentityPoolId identityProviderManager:pool];
    AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:CognitoIdentityIdentityPoolRegion credentialsProvider:credentialsProvider];
    AWSServiceManager.defaultServiceManager.defaultServiceConfiguration = configuration;
```

**Comment by behrooziAWS** [comment]
If you got the pattern that you were following from AWS documentation somewhere, let us know so we can make sure it is fixed.

**Comment by kdbertel** [comment]
I was creating the `AWSCognitoCredentialsProvider` first and passing it in to the `serviceConfiguration` because of the code sample [here](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/cognito-auth.html), in step 4 under "Providing AWS Credentials". In that case, the Credentials Provider is created, then given to the Service Configuration, which is then set. In the link you provided, the Service Configuration is set, and then the Credentials Provider is created using that as a base. The two seem to contradict each other as to the order things should happen; you can see why I was confused.

Creating a second `AWSServiceConfiguration` object and using it as the default appears to have solved all of my infinite loop problems for now, even around logging out. It was a solution I never thought of at all.

Is there documentation somewhere that indicates that two of them need to be created, one to get a session, and the second to actually use the user pools?

**Comment by behrooziAWS** [comment]
Ok, noted. It's more of a caveat than a contradiction, so I'll get the docs team to update that blurb to mention if you are using user pools it does not need a credentials provider and is initialized differently.

**Comment by kdbertel** [comment]
Okay, thanks. I'll close this issue, then, because it doesn't look like I'm still seeing it.
