### ISSUE TITLE
Expected member name or ';' after declaration specifiers into AWSCognitoIdentityProviderModel.h

### ISSUE THREAD

**Issue by zeitungen** [aws/aws-sdk-ios#597]
Hi,

I have this error Expected member name or ';' after declaration specifiers when the AWSCognitoIdentityProviderModel.h is compiling.
The concerned line is @property (nonatomic, strong) NSNumber * _Nullable mutable;

I guess is because mutable is a reserved keyword for C++.
But I use (and I need) C++ code in my project ...

What can I do to use properly the AWSCognitoIdentityProvider framework into my project ?
Thanks for your help !

**Comment by rohandubal** [comment]
Hi @zeitungen 

Could you please explain your use-case of how you are consuming the SDK? Are you using it in a C++ project?

Thanks,
Rohan

**Comment by zeitungen** [comment]
Rohan,

It's a C++ project with some Objective-C source files to destination of iOS devices.
I have to use the SDK, for now, for the AWS Cognito parts.
I have had the SDK (AWSCore, AWSCognito and AWSCognitoIdentityProvider) with the `framework` way (without CocoaPods or Carthage)

**Comment by karthiksaligrama** [comment]
Thanks this should be fixed with the next release.

**Comment by zeitungen** [comment]
Nice !
Any idea when the next release will be published ?

**Comment by minbi** [comment]
Released in v2.5.2

**Comment by seclorum** [comment]
Still getting this problem with AWSCognitoAuth (2.5.10), AWSCognitoIdentityProvider (2.4.16), and AWSCore (2.4.16) on a project with mixed Objective-C/Objective-C++ files.  Is there a cleaner way to fix this than renaming .mm -> .m files?
